-- GENERATED by "ontology and datasets/scripts/build_term_crosswalk.py" from
-- registration/cml_terms.json -- edit the JSON and regenerate, don't edit this file.
-- Idempotent: upserts terms and replaces the matches of every term listed here.

BEGIN;

INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('district', 'District', 'Second-order administrative division of India, identified by its LGD (Local Government Directory) district code. The LGD code is the canonical join key; names and census codes are alternate identifiers.', 'join_key', 'reference', NULL, ARRAY['district_lgd_code', 'District Code', 'district_name', 'District Name', 'District', 'DISTRICT', 'DT_CEN_CD', 'Census 2011 Code']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('state', 'State / Union Territory', 'First-order administrative division of India, identified by its LGD state code.', 'join_key', 'reference', NULL, ARRAY['state_lgd_code', 'State Code', 'state_name', 'State Name', 'State', 'ST_CEN_CD', 'report_state_label']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('city', 'City', 'Named city as reported by the data source (e.g. CPCB AQI bulletin). Mapped to a district where it lies in exactly one.', 'join_key', 'reference', NULL, ARRAY['city']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('latitude', 'Latitude', 'Latitude in decimal degrees (WGS84).', 'location', 'reference', 'http://qudt.org/vocab/unit/DEG', ARRAY['lat', 'latitude']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('longitude', 'Longitude', 'Longitude in decimal degrees (WGS84).', 'location', 'reference', 'http://qudt.org/vocab/unit/DEG', ARRAY['lon', 'lng', 'longitude']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('observation_date', 'Date', 'Calendar date (YYYY-MM-DD) the value refers to.', 'time', 'reference', NULL, ARRAY['date', 'last_update']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('aggregation_method', 'Aggregation method', 'How a gridded value was turned into a district value (e.g. area_mean_3_cells, nearest_cell).', 'provenance', 'reference', NULL, ARRAY['method']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('source_dataset', 'Source dataset', 'Identifier of the dataset a row came from.', 'provenance', 'reference', NULL, ARRAY['source_dataset']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('rainfall_daily', 'Daily rainfall', 'Total precipitation over one day, as depth of liquid water in mm.', 'measure', 'climate', 'http://qudt.org/vocab/unit/MilliM', ARRAY['rainfall_mm', 'precipitation', 'precip', 'prectotcorr', 'precipitation_sum', 'rain']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('air_temperature_max_daily', 'Daily maximum air temperature', 'Highest near-surface air temperature over one day, in degrees Celsius.', 'measure', 'climate', 'http://qudt.org/vocab/unit/DEG_C', ARRAY['temp_max_c', 't2m_max', 'temperature_2m_max', 'tmax', 'max_temp']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('air_temperature_min_daily', 'Daily minimum air temperature', 'Lowest near-surface air temperature over one day, in degrees Celsius.', 'measure', 'climate', 'http://qudt.org/vocab/unit/DEG_C', ARRAY['temp_min_c', 't2m_min', 'temperature_2m_min', 'tmin', 'min_temp']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('relative_humidity', 'Relative humidity', 'Near-surface relative humidity (daily mean), in percent.', 'measure', 'climate', 'http://qudt.org/vocab/unit/PERCENT_RH', ARRAY['relative_humidity_pct', 'rh2m', 'relative_humidity_2m_mean', 'rh', 'humidity']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('aqi', 'Air Quality Index (India NAQI)', 'India''s National Air Quality Index (0-500) for a city/station on a day, as published by CPCB.', 'measure', 'environment', 'http://qudt.org/vocab/unit/UNITLESS', ARRAY['aqi', 'AQI', 'aqi_value', 'air_quality_index']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('aqi_category', 'AQI category', 'NAQI band for the AQI value: Good, Satisfactory, Moderate, Poor, Very Poor, Severe.', 'measure', 'environment', NULL, ARRAY['aqi_category', 'air_quality']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('prominent_pollutant', 'Prominent pollutant', 'Pollutant(s) driving the day''s AQI (e.g. PM2.5, PM10, O3).', 'measure', 'environment', NULL, ARRAY['prominent_pollutant_raw', 'prominent_pollutant', 'pollutant_id']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('aqi_stations_reporting', 'Stations reporting', 'Monitoring stations that reported / total stations in the city, e.g. ''6/6''.', 'provenance', 'environment', NULL, ARRAY['stations_participated_total']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('pm25_concentration', 'PM2.5 concentration', 'Mass concentration of particulate matter <= 2.5 um in ambient air, in ug/m3.', 'measure', 'environment', 'http://qudt.org/vocab/unit/MicroGM-PER-M3', ARRAY['pm25', 'pm2_5', 'pm2.5', 'PM2.5', 'pollutant_id=PM2.5 / avg_value']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('pm10_concentration', 'PM10 concentration', 'Mass concentration of particulate matter <= 10 um in ambient air, in ug/m3.', 'measure', 'environment', 'http://qudt.org/vocab/unit/MicroGM-PER-M3', ARRAY['pm10', 'PM10', 'pollutant_id=PM10 / avg_value']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('electricity_energy_met_daily', 'Electricity energy met (daily)', 'Electrical energy supplied to consumers in a state over one day, in MU (million units = GWh).', 'measure', 'energy', 'http://qudt.org/vocab/unit/GigaW-HR', ARRAY['energy_met_mu', 'energy_met', 'energy_consumption_mu']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('electricity_peak_demand_met', 'Peak electricity demand met', 'Maximum electrical demand served in a state on a day, in MW.', 'measure', 'energy', 'http://qudt.org/vocab/unit/MegaW', ARRAY['max_demand_met_mw', 'peak_demand_mw', 'peak_demand_met']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('electricity_shortage_at_peak', 'Shortage at peak demand', 'Demand not served at the time of daily peak, in MW.', 'measure', 'energy', 'http://qudt.org/vocab/unit/MegaW', ARRAY['shortage_at_max_demand_mw', 'peak_shortage_mw']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('electricity_energy_shortage_daily', 'Electricity energy shortage (daily)', 'Electrical energy demanded but not supplied in a state over one day, in MU (GWh).', 'measure', 'energy', 'http://qudt.org/vocab/unit/GigaW-HR', ARRAY['energy_shortage_mu', 'energy_shortage']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('electricity_drawal_schedule_daily', 'Scheduled grid drawal (daily)', 'Electrical energy a state was scheduled to draw from the inter-state grid over one day, in MU (GWh).', 'measure', 'energy', 'http://qudt.org/vocab/unit/GigaW-HR', ARRAY['drawal_schedule_mu']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('electricity_overdrawal_daily', 'Grid over/under-drawal (daily)', 'Actual minus scheduled drawal from the inter-state grid over one day, in MU (GWh); negative = under-drawal.', 'measure', 'energy', 'http://qudt.org/vocab/unit/GigaW-HR', ARRAY['overdrawal_mu']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('anaemia_women_15_49_pct', 'Anaemia prevalence, women 15-49', 'Percent of women aged 15-49 who are anaemic (survey estimate, e.g. NFHS).', 'measure', 'health', 'http://qudt.org/vocab/unit/PERCENT', ARRAY['All women age 15-49 years who are anaemic (%)', 'anaemia_women', 'women_anaemic_pct']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('anaemia_children_6_59m_pct', 'Anaemia prevalence, children 6-59 months', 'Percent of children aged 6-59 months who are anaemic (survey estimate, e.g. NFHS).', 'measure', 'health', 'http://qudt.org/vocab/unit/PERCENT', ARRAY['Children age 6-59 months who are anaemic ', 'Children age 6-59 months who are anaemic (<11.0 g/dl) (%)', 'anaemia_children']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('high_blood_sugar_women_pct', 'High blood sugar, women', 'Percent of women with blood sugar >140 mg/dl or taking medicine to control it (survey estimate).', 'measure', 'health', 'http://qudt.org/vocab/unit/PERCENT', ARRAY['Female Blood sugar level  high or very high (>140 mg/dl) or taking medicine to control blood sugar level (%)']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('elevated_bp_women_pct', 'Elevated blood pressure, women', 'Percent of women with elevated blood pressure or taking medicine to control it (survey estimate).', 'measure', 'health', 'http://qudt.org/vocab/unit/PERCENT', ARRAY['Female Elevated blood pressure or taking medicine to control blood pressure (%)']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('stunting_under5_pct', 'Stunting, children under 5', 'Percent of children under 5 who are stunted (height-for-age below -2 SD).', 'measure', 'health', 'http://qudt.org/vocab/unit/PERCENT', ARRAY['Children under 5 years who are stunted (height for age) (%)', 'stunting', 'stunted_pct']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('wasting_under5_pct', 'Wasting, children under 5', 'Percent of children under 5 who are wasted (weight-for-height below -2 SD).', 'measure', 'health', 'http://qudt.org/vocab/unit/PERCENT', ARRAY['Children under 5 years who are wasted (weight for height) (%)', 'wasting', 'wasted_pct']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('institutional_births_pct', 'Institutional births', 'Percent of births in the survey reference period that took place in a health facility.', 'measure', 'health', 'http://qudt.org/vocab/unit/PERCENT', ARRAY['Institutional births (%)', 'Institutional births in the 5 years before the survey (%)', 'institutional_births']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('clean_cooking_fuel_households_pct', 'Households using clean cooking fuel', 'Percent of households whose main cooking fuel is clean (electricity, LPG/natural gas, biogas).', 'measure', 'health', 'http://qudt.org/vocab/unit/PERCENT', ARRAY['Households using clean fuel for cooking (%)', 'clean_cooking_fuel']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('survey_indicator_value', 'Survey indicator value', 'Value of a survey indicator for one survey round, in long-format data where the indicator name is in another column (NFHS: nfhs5_2019_21 = round 5, nfhs4_2015_16 = round 4).', 'measure', 'health', NULL, ARRAY['nfhs5_2019_21', 'nfhs4_2015_16', 'NFHS 5', 'NFHS 4']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('survey_indicator', 'Survey indicator name', 'Name of the indicator a long-format survey row reports (resolve to a term via the indicator synonyms above).', 'measure', 'health', NULL, ARRAY['indicator', 'Indicator']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();
INSERT INTO cml_term (term_key, label, definition, category, domain, unit_uri, synonyms) VALUES ('survey_indicator_category', 'Survey indicator category', 'Section the indicator belongs to (e.g. ''Population and Household Profile'').', 'measure', 'health', NULL, ARRAY['category', 'Category']::TEXT[])
  ON CONFLICT (term_key) DO UPDATE SET label = EXCLUDED.label, definition = EXCLUDED.definition,
    category = EXCLUDED.category, domain = EXCLUDED.domain, unit_uri = EXCLUDED.unit_uri,
    synonyms = EXCLUDED.synonyms, updated_at = NOW();

DELETE FROM cml_term_ontology_match WHERE term_key IN ('district', 'state', 'city', 'latitude', 'longitude', 'observation_date', 'aggregation_method', 'source_dataset', 'rainfall_daily', 'air_temperature_max_daily', 'air_temperature_min_daily', 'relative_humidity', 'aqi', 'aqi_category', 'prominent_pollutant', 'aqi_stations_reporting', 'pm25_concentration', 'pm10_concentration', 'electricity_energy_met_daily', 'electricity_peak_demand_met', 'electricity_shortage_at_peak', 'electricity_energy_shortage_daily', 'electricity_drawal_schedule_daily', 'electricity_overdrawal_daily', 'anaemia_women_15_49_pct', 'anaemia_children_6_59m_pct', 'high_blood_sugar_women_pct', 'elevated_bp_women_pct', 'stunting_under5_pct', 'wasting_under5_pct', 'institutional_births_pct', 'clean_cooking_fuel_households_pct', 'survey_indicator_value', 'survey_indicator', 'survey_indicator_category');

INSERT INTO cml_term_ontology_match (term_key, ontology_graph_key, term_uri, term_label, match_type, is_primary, note) VALUES
  ('district', 'envo', 'http://purl.obolibrary.org/obo/ENVO_00000006', 'second-order administrative region', 'close', TRUE, 'second-order administrative region; ''district'' is the Indian name for this level'),
  ('district', 'envo', 'http://purl.obolibrary.org/obo/ENVO_00000004', 'administrative region', 'broader', FALSE, 'administrative region; ENVO lists ''district'' as a related synonym'),
  ('district', 'sweet', 'http://sweetontology.net/humanJurisdiction/AdministrativeRegion', 'administrative region', 'broader', FALSE, NULL),
  ('district', 'geosparql', 'http://www.opengis.net/ont/geosparql#Feature', NULL, 'broader', FALSE, 'district boundary is published as a GeoSPARQL feature / GeoServer layer'),
  ('state', 'envo', 'http://purl.obolibrary.org/obo/ENVO_00000005', 'first-order administrative region', 'exact', TRUE, 'first-order administrative region, ''such as a state in the United States'''),
  ('state', 'sweet', 'http://sweetontology.net/humanJurisdiction/State', 'state', 'exact', FALSE, NULL),
  ('state', 'sweet', 'http://sweetontology.net/humanJurisdiction/AdministrativeRegion', 'administrative region', 'broader', FALSE, NULL),
  ('state', 'geosparql', 'http://www.opengis.net/ont/geosparql#Feature', NULL, 'broader', FALSE, NULL),
  ('city', 'envo', 'http://purl.obolibrary.org/obo/ENVO_00000856', 'city', 'exact', TRUE, NULL),
  ('city', 'sweet', 'http://sweetontology.net/humanJurisdiction/City', 'city', 'exact', FALSE, NULL),
  ('latitude', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/CFSN0600/', 'latitude', 'exact', TRUE, NULL),
  ('latitude', 'sweet', 'http://sweetontology.net/reprSpaceCoordinate/Latitude', 'latitude', 'exact', FALSE, NULL),
  ('longitude', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/CFSN0554/', 'longitude', 'exact', TRUE, NULL),
  ('longitude', 'sweet', 'http://sweetontology.net/reprSpaceCoordinate/Longitude', 'longitude', 'exact', FALSE, NULL),
  ('observation_date', 'sosa', 'http://www.w3.org/ns/sosa/phenomenonTime', 'phenomenon time', 'close', TRUE, 'SOSA property: the time the observed property applies to'),
  ('observation_date', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/CFSN0115/', 'time', 'broader', FALSE, 'CF time coordinate'),
  ('observation_date', 'sweet', 'http://sweetontology.net/reprTime/Time', 'time', 'broader', FALSE, NULL),
  ('aggregation_method', 'sosa', 'http://www.w3.org/ns/sosa/Procedure', 'Procedure', 'related', TRUE, NULL),
  ('source_dataset', 'dcat3', 'http://www.w3.org/ns/dcat#Dataset', 'Dataset', 'related', TRUE, 'the column holds an identifier of a dcat:Dataset'),
  ('rainfall_daily', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/CFSN0569/', 'lwe_thickness_of_precipitation_amount', 'exact', TRUE, 'lwe_thickness_of_precipitation_amount; daily total via CF cell_methods time: sum'),
  ('rainfall_daily', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/CFSN0452/', 'precipitation_amount', 'close', FALSE, 'precipitation_amount in kg m-2; numerically equal to mm of water'),
  ('rainfall_daily', 'sweet', 'http://sweetontology.net/propSpaceThickness/Precipitation', 'precipitation', 'close', FALSE, 'precipitation as a thickness/water-content property'),
  ('rainfall_daily', 'sweet', 'http://sweetontology.net/phenAtmoPrecipitation/Rainfall', 'rainfall', 'related', FALSE, 'the rainfall phenomenon'),
  ('rainfall_daily', 'sweet', 'http://sweetontology.net/phen/Precipitation', 'precipitation', 'related', FALSE, 'the precipitation phenomenon'),
  ('rainfall_daily', 'envo', 'http://purl.obolibrary.org/obo/ENVO_01001363', 'volume of hydrological precipitation', 'related', FALSE, 'volume of hydrological precipitation (volume, not depth)'),
  ('rainfall_daily', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/Length', 'Length', 'broader', FALSE, 'quantity kind of a depth in mm'),
  ('air_temperature_max_daily', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/CFSN0023/', 'air_temperature', 'broader', TRUE, 'air_temperature; daily max via CF cell_methods time: maximum'),
  ('air_temperature_max_daily', 'envo', 'http://purl.obolibrary.org/obo/ENVO_09200001', 'temperature of air', 'broader', FALSE, 'temperature of air'),
  ('air_temperature_max_daily', 'sweet', 'http://sweetontology.net/propTemperature/Temperature', 'temperature', 'broader', FALSE, NULL),
  ('air_temperature_max_daily', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/Temperature', 'Temperature', 'broader', FALSE, NULL),
  ('air_temperature_min_daily', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/CFSN0023/', 'air_temperature', 'broader', TRUE, 'air_temperature; daily min via CF cell_methods time: minimum'),
  ('air_temperature_min_daily', 'envo', 'http://purl.obolibrary.org/obo/ENVO_09200001', 'temperature of air', 'broader', FALSE, 'temperature of air'),
  ('air_temperature_min_daily', 'sweet', 'http://sweetontology.net/propTemperature/Temperature', 'temperature', 'broader', FALSE, NULL),
  ('air_temperature_min_daily', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/Temperature', 'Temperature', 'broader', FALSE, NULL),
  ('relative_humidity', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/CFSN0413/', 'relative_humidity', 'exact', TRUE, NULL),
  ('relative_humidity', 'sweet', 'http://sweetontology.net/propFraction/RelativeHumidity', 'relative humidity', 'exact', FALSE, NULL),
  ('relative_humidity', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/RelativeHumidity', 'Relative Humidity', 'exact', FALSE, NULL),
  ('aqi', 'sweet', 'http://sweetontology.net/propIndex/AirQualityIndex', 'air quality index', 'broader', TRUE, 'generic air quality index; India''s NAQI is one specific AQI'),
  ('aqi', 'sweet', 'http://sweetontology.net/phenEnvirImpact/AirQuality', 'air quality', 'related', FALSE, NULL),
  ('aqi', 'envo', 'http://purl.obolibrary.org/obo/ENVO_02500037', 'air pollution', 'related', FALSE, 'air pollution (process)'),
  ('aqi', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00000055', 'air pollution', 'related', FALSE, 'air pollution'),
  ('aqi_category', 'sweet', 'http://sweetontology.net/phenEnvirImpact/AirQuality', 'air quality', 'related', TRUE, NULL),
  ('aqi_category', 'sweet', 'http://sweetontology.net/propIndex/AirQualityIndex', 'air quality index', 'related', FALSE, NULL),
  ('prominent_pollutant', 'envo', 'http://purl.obolibrary.org/obo/ENVO_02500037', 'air pollution', 'related', TRUE, 'air pollution; no ''air pollutant'' class in the loaded ontologies'),
  ('aqi_stations_reporting', 'sosa', 'http://www.w3.org/ns/sosa/Sensor', 'Sensor', 'related', TRUE, 'count of sensors/stations behind the value'),
  ('pm25_concentration', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/YUDG9DXK/', 'mass_concentration_of_pm2p5_ambient_aerosol_particles_in_air', 'exact', TRUE, 'mass_concentration_of_pm2p5_ambient_aerosol_particles_in_air'),
  ('pm25_concentration', 'envo', 'http://purl.obolibrary.org/obo/ENVO_01000415', 'fine respirable suspended particulate matter', 'related', FALSE, 'the material (fine respirable suspended particulate matter), not its concentration'),
  ('pm25_concentration', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00010010', 'PM2.5', 'related', FALSE, 'the material PM2.5'),
  ('pm25_concentration', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/MassConcentration', 'Mass Concentration', 'broader', FALSE, NULL),
  ('pm10_concentration', 'cf-standard-names', 'http://vocab.nerc.ac.uk/collection/P07/current/6O34XRFW/', 'mass_concentration_of_pm10_ambient_aerosol_particles_in_air', 'exact', TRUE, 'mass_concentration_of_pm10_ambient_aerosol_particles_in_air'),
  ('pm10_concentration', 'envo', 'http://purl.obolibrary.org/obo/ENVO_01000405', 'respirable suspended particulate matter', 'related', FALSE, 'the material (respirable suspended particulate matter)'),
  ('pm10_concentration', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00010009', 'PM10', 'related', FALSE, 'the material PM10'),
  ('pm10_concentration', 'sweet', 'http://sweetontology.net/matrAerosol/PM10', 'pm10', 'related', FALSE, 'the material PM10'),
  ('pm10_concentration', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/MassConcentration', 'Mass Concentration', 'broader', FALSE, NULL),
  ('electricity_energy_met_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00320062', 'electricity demand', 'close', TRUE, 'electricity demand; ''met'' = demand actually served'),
  ('electricity_energy_met_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00020204', 'electrical energy amount value', 'broader', FALSE, 'electrical energy amount value'),
  ('electricity_energy_met_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00000139', 'electrical energy', 'broader', FALSE, 'electrical energy'),
  ('electricity_energy_met_daily', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/Energy', 'Energy', 'broader', FALSE, NULL),
  ('electricity_peak_demand_met', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00320062', 'electricity demand', 'close', TRUE, 'electricity demand; value is the daily peak in MW'),
  ('electricity_peak_demand_met', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00010157', 'power value', 'broader', FALSE, 'power value'),
  ('electricity_peak_demand_met', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/ElectricPower', 'Electric Power', 'broader', FALSE, NULL),
  ('electricity_shortage_at_peak', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00320062', 'electricity demand', 'related', TRUE, 'electricity demand (unmet part); no ''shortage'' class in OEO'),
  ('electricity_shortage_at_peak', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/ElectricPower', 'Electric Power', 'broader', FALSE, NULL),
  ('electricity_energy_shortage_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00320062', 'electricity demand', 'related', TRUE, 'electricity demand (unmet part)'),
  ('electricity_energy_shortage_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00140146', 'energy demand', 'related', FALSE, 'energy demand (the term datasets.json used)'),
  ('electricity_energy_shortage_daily', 'qudt-quantitykind', 'http://qudt.org/vocab/quantitykind/Energy', 'Energy', 'broader', FALSE, NULL),
  ('electricity_drawal_schedule_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00320036', 'electrical energy transfer', 'related', TRUE, 'electrical energy transfer'),
  ('electricity_drawal_schedule_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00020204', 'electrical energy amount value', 'broader', FALSE, 'electrical energy amount value'),
  ('electricity_overdrawal_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00320036', 'electrical energy transfer', 'related', TRUE, 'electrical energy transfer'),
  ('electricity_overdrawal_daily', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00020204', 'electrical energy amount value', 'broader', FALSE, 'electrical energy amount value'),
  ('anaemia_women_15_49_pct', 'doid', 'http://purl.obolibrary.org/obo/DOID_2355', 'anemia', 'related', TRUE, 'anemia (the disease; our term is its prevalence)'),
  ('anaemia_children_6_59m_pct', 'doid', 'http://purl.obolibrary.org/obo/DOID_2355', 'anemia', 'related', TRUE, 'anemia (the disease; our term is its prevalence)'),
  ('high_blood_sugar_women_pct', 'doid', 'http://purl.obolibrary.org/obo/DOID_9351', 'diabetes mellitus', 'related', TRUE, 'diabetes mellitus; high blood sugar is an indicator, not a diagnosis'),
  ('elevated_bp_women_pct', 'doid', 'http://purl.obolibrary.org/obo/DOID_10763', 'hypertension', 'related', TRUE, 'hypertension'),
  ('stunting_under5_pct', 'doid', 'http://purl.obolibrary.org/obo/DOID_11801', 'protein-energy malnutrition', 'related', TRUE, 'protein-energy malnutrition; DOID has no stunting class'),
  ('wasting_under5_pct', 'doid', 'http://purl.obolibrary.org/obo/DOID_11801', 'protein-energy malnutrition', 'related', TRUE, 'protein-energy malnutrition; DOID has no wasting class. NOT sweet:phenSolid/Wasting (mass wasting)'),
  ('clean_cooking_fuel_households_pct', 'envo', 'http://purl.obolibrary.org/obo/ENVO_01000553', 'liquefied petroleum gas', 'related', TRUE, 'liquefied petroleum gas, the main clean cooking fuel in India'),
  ('clean_cooking_fuel_households_pct', 'oeo', 'https://openenergyplatform.org/ontology/oeo/OEO_00320011', 'liquefied petroleum gas', 'related', FALSE, 'liquefied petroleum gas'),
  ('survey_indicator_value', 'qb', 'http://purl.org/linked-data/cube#Observation', 'Observation', 'related', TRUE, 'each row is a Data Cube observation; indicator = measure, round = dimension'),
  ('survey_indicator_value', 'sosa', 'http://www.w3.org/ns/sosa/Observation', 'Observation', 'related', FALSE, NULL),
  ('survey_indicator', 'qb', 'http://purl.org/linked-data/cube#MeasureProperty', 'Measure property', 'related', TRUE, NULL);

COMMIT;
